# Configurations
title:            Intro
longtitle:        The Official Guide to Knex Ball Machine Lifts
author:           Shadowman39
email:            ...
description: >
  Discover a comprehensive guide to K'NEX ball machine lifts with unique designs, instructions, and tips for builders—start building today!

version:          1.0
gitbook_version:  3.2.3

url:              'https://shadowman39.github.io'
baseurl:          '/official-lift-guide'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 2
  h_max: 3

tracker:
  google_analytics: "G-55GG8CZVQ3"

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/img/favicon3.png

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             2..3
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  about:
    output: true
    permalink: /:collection/:path/
  lifts:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-sitemap
